#!/bin/bash

set -e

# Get list of staged files (Added, Copied, Modified)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

# If nothing staged, skip
if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

make csfix-hook

echo "Re-adding previously staged files..."

# Re-add only files that were originally staged
for file in $STAGED_FILES; do
  if [ -f "$file" ]; then
    git add "$file"
  fi
done

exit 0